<?php
/** @var $block \Mirasvit\Blog\Block\Post\PostList\Toolbar */
?>
<div class="field limiter">
    <label class="label" for="limiter">
        <span><?= __('Show') ?></span>
    </label>
    <div class="control">
        <select id="limiter" data-role="limiter" class="limiter-options">
            <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                <option value="<=$_key ?>"
                        <?php if ($block->isLimitCurrent($_key)): ?>selected="selected"<?php endif ?>>
                    <?= $_limit ?>
                </option>
            <?php endforeach ?>
        </select>
    </div>
    <span class="limiter-text"><?= __('per page') ?></span>
</div>
