<?php
/** @var $block \Mirasvit\Blog\Block\Post\PostList\Toolbar */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $key => $order): ?>
            <option value="<?= $key ?>"
                <?php if ($block->isOrderCurrent($key)): ?> selected="selected"<?php endif ?>
            >
                <?= $block->escapeHtml(__($order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc"
           data-role="direction-switcher" data-value="asc">
            <span><?= __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc"
           data-role="direction-switcher" data-value="desc">
            <span><?= __('Set Descending Direction') ?></span>
        </a>
    <?php endif ?>
</div>
