<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\Meta $block */

// solve error with template minification
$countJs = '//';
$countJs .= $block->getDisqusShortname() . '.disqus.com/count.js';
?>

<?php if ($block->getCommentProvider()): ?>
    <script id="dsq-count-scr" src="<?= $countJs ?>"></script>
<?php endif ?>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-554788110b283abc"></script>