<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\Meta $block */
?>

<?php if ($block->getCommentProvider()): ?>
    <script id="dsq-count-scr" src="//<?= $block->getDisqusShortname() ?>.disqus.com/count.js"></script>
<?php endif ?>

<!-- Go to www.addthis.com/dashboard to customize your tools -->
<script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-554788110b283abc"></script>