<?php
//@codingStandardsIgnoreFile

/** @var Meta $block */

// solve error with template minification
use Mirasvit\Blog\Block\Post\Meta;

$countJs = '//';
$countJs .= $block->getDisqusShortname() . '.disqus.com/count.js';
?>

<?php if ($block->getCommentProvider() == 'discus'): ?>
    <script id="dsq-count-scr" src="<?= $countJs ?>"></script>
<?php endif ?>

<?php if ($block->getCommentProvider() == 'facebook'): ?>
    <div id="fb-root"></div>
    <script>(function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.6";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
<?php endif ?>

<?php if ($block->isAddThisEnabled()): ?>
    <!-- Go to www.addthis.com/dashboard to customize your tools -->
    <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-554788110b283abc"></script>
<?php endif ?>