<?php
//@codingStandardsIgnoreFile

/** @var $block CategoryTree */

use Mirasvit\Blog\Block\Sidebar\CategoryTree; ?>

<div class="block block-collapsible-nav blog__sidebar-category-tree">
    <div class="title block-collapsible-nav-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-blog", "selectorsToggleClass": "active"}}'>
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-collapsible-content content" id="block-collapsible-nav-blog">
        <ul class="nav items">
            <?php foreach ($block->getTree() as $category): ?>
                <li class="nav item level-<?= $category->getLevel() ?> <?php if ($block->isCurrent($category)): ?>current<?php endif ?>">
                    <a href="<?= $category->getUrl() ?>"><?= $category->getName() ?></a>
                </li>
            <?php endforeach ?>
        </ul>
    </div>
</div>
