<?php
/** @var \Mirasvit\Blog\Block\Post\PostList $block */
$collection = $block->getPostCollection();
?>

<?php if ($collection->count()): ?>
    <?php echo $block->getToolbarHtml() ?>

    <ol class="blog__post-list">
        <?php foreach ($collection as $post): ?>
            <li class="blog__post-list-item">
                <h2><a href="<?= $post->getUrl() ?>" class="post-link"><?= $post->getName() ?></a></h2>
                <?= $post->getShortContent() ?>
            </li>
        <?php endforeach ?>
    </ol>

    <?php echo $block->getToolbarHtml() ?>
<?php else: ?>
    <p><?= __('There are no posts available for this category') ?></p>
<?php endif ?>
