<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Post\View $block */
$post = $block->getPost();
?>

<div class="blog__post-view">

    <?= $this->getPostMetaHeader()->toHtml() ?>

    <?php if ($post->getFeaturedImageUrl()): ?>
        <img src="<?= $post->getFeaturedImageUrl() ?>" class="blog__post-featured-image"/>
    <?php endif ?>

    <?= $post->getShortContent() ?>

    <?= $block->getPostContent() ?>

    <?= $this->getPostMetaFooter()->toHtml() ?>

    <?= $this->getChildHtml('blog.post.related') ?>

    <?= $this->getChildHtml('blog.post.comments') ?>
</div>