<?php
/** @var $block Toolbar */

use Mirasvit\Blog\Block\Post\PostList\Toolbar;

?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNum() > 1): ?>
        <?= __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
            '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php elseif ($block->getTotalNum() == 1): ?>
        <?= __('%1 Item', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php else: ?>
        <?= __('%1 Items', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>') ?>
    <?php endif ?>
</p>
