<?php
//@codingStandardsIgnoreFile

/** @var View $block */
$post = $block->getPost();

use Mirasvit\Blog\Block\Post\View; ?>

<div class="blog__post-view">

    <?= $this->getPostMetaHeader()->toHtml() ?>

    <?php if ($post->getFeaturedImageUrl()): ?>
        <img src="<?= $post->getFeaturedImageUrl() ?>" alt="<?= $post->getName() ?>" class="blog__post-featured-image"/>
    <?php endif ?>

    <?= $block->getPostContent() ?>

    <?= $this->getPostMetaFooter()->toHtml() ?>

    <?= $this->getChildHtml('blog.post.related.posts') ?>

    <?= $this->getChildHtml('blog.post.related.products') ?>

    <?= $this->getChildHtml('blog.post.comments') ?>
</div>
