<?php
//@codingStandardsIgnoreFile

/** @var RelatedPosts $block */
$collection = $block->getPostCollection()
    ->setPageSize(4);

if (!$collection->count()) {
    return;
}

use Mirasvit\Blog\Block\Post\View\RelatedPosts; ?>

<div class="blog__post-view-related-posts">
    <div class="block-title"><?= __('Related Posts') ?></div>
    <ol>
        <?php foreach ($collection as $post): ?>
            <li>
                <?php if ($post->getFeaturedImageUrl()): ?>
                    <img src="<?= $post->getFeaturedImageUrl() ?>" alt="<?= $post->getName() ?>" class="post-image"/>
                <?php endif ?>

                <a href="<?= $post->getUrl() ?>" class="post-name"><?= $post->getName() ?></a>

                <?= mb_substr(strip_tags($post->getShortContent()), 0, 250) ?>
            </li>
        <?php endforeach ?>
    </ol>
</div>
